version: "3.8"
services: 
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:8080"
    links:
      - nginx_my


  nginx_my:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    
